spring:
  profiles:
    default: dev
  application:
    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: test_route
#          uri: http://localhost:11434
#          predicates:
#            - Path=/api/*
#          filters:
#            - name: Test2Filter

host:
  url: http://localhost:11434

app:
  server:
    lineseparator: "\n"
  message:
    encrypted: true
    enc_key: "my_very_secret_key_32_bytes_long"
    logging:
      level: INFO

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    com.chatbot.gateway: TRACE
