{
 "title": "Request Time",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Gateway request processing time(ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gateway_request_proxy_time_seconds_sum / gateway_request_proxy_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway response processing time(ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gateway_response_proxy_time_seconds_sum / gateway_response_proxy_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request encrypt time(sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "gateway_request_processing_time_seconds_sum /  gateway_request_processing_time_seconds_count",
     "legendFormat": "decrypt, verify time"
    }
   ]
  },
  {
   "title": "Request content length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "gateway_request_content_length", "legendFormat": "content length" }
   ]
  },
  {
   "title": "Response encrypt time(sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "gateway_response_processing_time_seconds_sum /  gateway_response_processing_time_seconds_count",
     "legendFormat": "decrypt, verify time"
    }
   ]
  },
  {
   "title": "Response enctypt content length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "gateway_response_content_length",
     "legendFormat": "content length"
    }
   ]
  },
  {
   "title": "Global processing time(sec)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "gateway_global_processing_time_seconds_sum / gateway_global_processing_time_seconds_count",
     "legendFormat": "gateway filter total time"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "targets": [
    { "expr": "gateway_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}